CREATE TABLE "USER1"."CUSTOMER"
(
   CUSTOMER_ID bigint PRIMARY KEY NOT NULL,
   FIRST_NM varchar(30) NOT NULL,
   LAST_NM varchar(50) NOT NULL,
   GENDER char(1) NOT NULL,
   BIRTH_DT date NOT NULL,
   DEATH_DT date
)
;
CREATE UNIQUE INDEX SQL130402203018020 ON "USER1"."CUSTOMER"(CUSTOMER_ID)
;
